baseURL: 'https://dev.galileocap.me/'
languageCode: 'en-us'
title: 'GalileoCap'
theme: 'PaperMod'

enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  title: GalileoCap
  description: "My personal website"
  keywords: [Blog, Portfolio]
  author: Galileo Cappella

  defaultTheme: "auto"
  DateFormat: "02 Jan, 2006"
  ShowBreadCrumbs: true
  #ShowShareButtons: true
  ShowCodeCopyButtons: true
  tocopen: false
  ShowPostNavLinks: true
  #ShareButtons: ["twitter", "linkedin", "reddit", "whatsapp", "telegram"]
  #ShowWordCount: true
  comments: false
  hideFooter: true

  #analytics.google.SiteVerificationTag: TODO
  
  #TODO cover: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/#cover

  homeInfoParams:
    Title: "GalilepCap"
    Content: Welcome to my personal site #TODO

  socialIcons: # optional
    #- name: "Email"
      #url: mailto:contact@galileocap.me
    - name: "GitHub"
      url: https://github.com/galileocap
    #- name: "GitLab"
      #url: https://gitlab.com/GalileoCap
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/galileocap"

  #editPost:
    #URL: "https://github.com/<path_to_repo>/content"
    #Text: "Suggest Changes" # edit text
    #appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: osdev
      name: OSDev
      url: /osdev/
      weight: 20
    - identifier: games
      name: Games
      url: /games/
      weight: 30
    - identifier: ttrpg
      name: TTRPG
      url: /ttrpg/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 98
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 99
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 100

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
